### ISSUE TITLE
有关send()调用返值与发送缓冲长度不符时处理的疑问

### ISSUE THREAD

**Issue by qinggniq** [balloonwj/easyserverdev#2]
https://github.com/balloonwj/easyserverdev/blob/f478c0fb28a106ff3fd0b84121c7a06152c31a46/code/server.cpp#L59
```c++
if (ret != strlen(recvBuf))
	std::cout << "send data error." << std::endl;
				
std::cout << "send data to client successfully, data: " << recvBuf << std::endl;
```
如上代码会输出`"send data error.\n"`，然后在下面一行
依然会输出`"send data to client successfully, data: "+recvBuf`。我觉得正确的应该是这样处理：
```c++
if (ret != strlen(recvBuf))
	std::cout << "send data error." << std::endl;
else			
        std::cout << "send data to client successfully, data: " << recvBuf << std::endl;
```

**Comment by balloonwj** [comment]
@qinggniq 你的想法是对的，这里只是简单地认为一次性发数据能发出去指定的长度，是可以按你的想法来修改一下。
